/**
 * Created by askorodumov on 24.09.17.
 */
export const SET_CURRENT_USER     = 'SET_CURRENT_USER'
export const FETCH_LOGIN_REQUEST  = 'FETCH_LOGIN_REQUEST'
export const FETCH_LOGIN_SUCCESS  = 'FETCH_LOGIN_SUCCESS'
export const FETCH_LOGIN_FAIL     = 'FETCH_LOGIN_FAIL'
export const FETCH_LOGOUT_REQUEST = 'FETCH_LOGOUT_REQUEST'
export const FETCH_LOGOUT_SUCCESS = 'FETCH_LOGOUT_SUCCESS'
export const FETCH_LOGOUT_FAIL    = 'FETCH_LOGOUT_FAIL'
export const FETCH_DRAFT_REQUEST  = 'FETCH_DRAFT_REQUEST'
export const FETCH_DRAFT_SUCCESS  = 'FETCH_DRAFT_SUCCESS'
export const FETCH_DRAFT_FAIL     = 'FETCH_DRAFT_FAIL'
export const FETCH_PRICE_REQUEST  = 'FETCH_PRICE_REQUEST'
export const FETCH_PRICE_SUCCESS  = 'FETCH_PRICE_SUCCESS'
export const FETCH_PRICE_FAIL     = 'FETCH_PRICE_FAIL'
export const FETCH_LEADS_REQUEST  = 'FETCH_LEADS_REQUEST'
export const FETCH_LEADS_SUCCESS  = 'FETCH_LEADS_SUCCESS'
export const FETCH_LEADS_FAIL     = 'FETCH_LEADS_FAIL'